spring:
  application:
    name: mina-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.10.10.148:8848
        username: nacos
        password: nacos
        namespace: 0efc12c9-8f03-4a24-9e22-18c473db25fa
        group: mina-cloud #项目名
project:
  name: mina-consumer
server:
  port: 8081
#logging:
#    config: classpath:logback-spring.xml
#    file:
#      path: ./
#      name: ${spring.application.name}

# 开启金丝雀负载均衡
mina:
  cloud:
    discovery:
      canary:
        enable: true
        # 指定自定义流量标记
        tag: 920104