spring:
  application:
    name: mina-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 0efc12c9-8f03-4a24-9e22-18c473db25fa
        group: mina-cloud1
project:
  name: ${spring.application.name}

---
# 开启金丝雀负载均衡
mina:
  cloud:
    discovery:
      canary:
        enable: true
        # 指定自定义流量标记
        tag: 920104