spring:
  application:
    name: mina-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 52e671fa-26ea-48b5-938b-865e935f527f
        group: mina-cloud #???
project:
  name: mina-provider

